DEVICE = "cuda"
DTYPE = "bfloat16"
DATA_PATH = "../anki-revlogs-10k"

LMDB_PATH = "test_db_short_secs"
LMDB_SIZE = 195_000_000_000
LABEL_FILTER_LMDB_PATH = "label_filter_db"
LABEL_FILTER_LMDB_SIZE = 12_000_000_000
LABEL_FILTER_KEY_PREFIX = "short_secs_"

USER_START = 1
USER_END = 10000
MAX_BATCH_SIZE = 2097152
RWKV_SUBMODULES = ["card_id", "note_id", "deck_id", "preset_id", "user_id"]
