DATA_PATH = "../anki-revlogs-10k"

# Reuse the same LMDB, but store a separate keyset (so it won't overwrite the default no-same-day keys).
LABEL_FILTER_LMDB_PATH = "label_filter_db"
# Increase map size if you store multiple keysets in the same LMDB.
LABEL_FILTER_LMDB_SIZE = 12_000_000_000
LABEL_FILTER_KEY_PREFIX = "short_secs_"

USER_START = 1
USER_END = 10000

PROCESSES = 9
